// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestSeleniumNumero1 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
@Test
public void testSeleniumNumero1() {
        driver.get("https://www.onlineconversion.com/temperature.htm");
        driver.manage().window().setSize(new Dimension(974, 1032));
        driver.findElement(By.name("what")).click();
        driver.findElement(By.name("what")).sendKeys("255");
        {
        WebElement dropdown = driver.findElement(By.name("from"));
        dropdown.findElement(By.xpath("//option[. = 'degree Rankine']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(1) option:nth-child(3)")).click();
        {
        WebElement dropdown = driver.findElement(By.name("to"));
        dropdown.findElement(By.xpath("//option[. = 'kelvin']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) option:nth-child(5)")).click();
        driver.findElement(By.name("Go")).click();
        driver.findElement(By.name("what")).click();
        driver.findElement(By.name("what")).sendKeys("196");
        {
        WebElement dropdown = driver.findElement(By.name("from"));
        dropdown.findElement(By.xpath("//option[. = 'degree Celsius']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(1) option:nth-child(1)")).click();
        {
        WebElement dropdown = driver.findElement(By.name("to"));
        dropdown.findElement(By.xpath("//option[. = 'degree Fahrenheit']")).click();
        }
        driver.findElement(By.cssSelector("td:nth-child(2) option:nth-child(2)")).click();
        driver.findElement(By.name("Go")).click();
        driver.findElement(By.cssSelector("table")).click();
        driver.findElement(By.name("what")).click();
        }
        }


